# Generated by Django 4.2.2 on 2023-11-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='lote_producto',
        ),
    ]
