# Generated by Django 4.2.2 on 2023-11-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='numero_lote',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
