# Generated by Django 4.2.2 on 2023-11-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=150, null=True)),
                ('tipo_persona', models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor')], max_length=255, null=True)),
            ],
        ),
    ]
